In [1]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(trian_x, train_y), (test_x, test_y) = mnist.load_data()
trian_x, test_x = trian_x / 255., test_x / 255.

In [2]:
print(trian_x.shape)

(60000, 28, 28)


In [3]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [4]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dropout (Dropout)            (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [5]:
prediction = model(trian_x[:1]).numpy()
prediction

array([[-0.08482969, -0.35888028, -0.13145636,  0.66773427, -0.6447163 ,
        -0.16765623,  0.59971315,  0.02321998, -0.27523512,  0.25434786]],
      dtype=float32)

In [6]:
tf.nn.softmax(prediction).numpy()

array([[0.08579021, 0.06522575, 0.08188192, 0.18208413, 0.0490097 ,
        0.07897081, 0.17011042, 0.09557913, 0.07091624, 0.12043165]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(train_y[:1], prediction).numpy()

2.538677

In [8]:
model.compile(optimizer='adam', loss=loss_fn, metrics=['accuracy'])
model.fit(trian_x, train_y, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.4825 - accuracy: 0.8598
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1476 - accuracy: 0.9562
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1028 - accuracy: 0.9686
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0820 - accuracy: 0.9743
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0712 - accuracy: 0.9780


In [9]:
model.evaluate(test_x, test_y, verbose=2)

313/313 - 0s - loss: 0.0779 - accuracy: 0.9753


[0.07788392901420593, 0.9753000140190125]

In [10]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [12]:
probability_model(test_x[:1])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[2.3887791e-08, 7.5406547e-08, 5.3136359e-06, 5.4237782e-04,
        9.0629011e-11, 4.0788115e-07, 4.0044443e-12, 9.9940681e-01,
        1.1092403e-08, 4.5025830e-05]], dtype=float32)>

In [13]:
model(test_x[:1])

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[ -7.3870654 ,  -6.237539  ,  -1.982401  ,   2.6432858 ,
        -12.961412  ,  -4.549456  , -16.080784  ,  10.16224   ,
         -8.154172  ,   0.15455934]], dtype=float32)>